# Generated by Django 5.2.17 on 2026-08-17 12:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="Código (ticker)"
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nome da empresa"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Ativo",
                "verbose_name_plural": "Ativos",
                "ordering": ["ticker"],
            },
        ),
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("LUCRO", "Meta de lucro atingida"),
                            ("PERDA", "Meta de perda atingida"),
                            ("TENDENCIA", "Sinal de tendência de mercado"),
                            ("LEMBRETE", "Lembrete geral"),
                        ],
                        max_length=12,
                    ),
                ),
                ("mensagem", models.CharField(max_length=255)),
                (
                    "percentual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("lido", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ativo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="core.ativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Operacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("COMPRA", "Compra"), ("VENDA", "Venda")], max_length=6
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(verbose_name="Quantidade")),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Preço unitário (R$)",
                    ),
                ),
                (
                    "data_operacao",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data da operação",
                    ),
                ),
                (
                    "meta_lucro_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Meta de lucro (%)",
                    ),
                ),
                (
                    "meta_perda_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Meta de perda (%) - use valor negativo",
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "ativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operacoes",
                        to="core.ativo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Operação",
                "verbose_name_plural": "Operações",
                "ordering": ["-data_operacao", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Cotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data da cotação")),
                (
                    "preco_fechamento",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Preço de fechamento (R$)",
                    ),
                ),
                (
                    "variacao_dia_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Variação no dia (%)",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "ativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotacoes",
                        to="core.ativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotação",
                "verbose_name_plural": "Cotações",
                "ordering": ["-data"],
                "unique_together": {("ativo", "data")},
            },
        ),
    ]
