# Generated by Django 5.2.17 on 2026-08-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(max_length=150, verbose_name='Remetente (nome ou número)')),
                ('texto', models.TextField(verbose_name='Mensagem')),
                ('recebido_em', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
            ],
            options={
                'verbose_name': 'Mensagem do WhatsApp',
                'verbose_name_plural': 'Mensagens do WhatsApp',
                'ordering': ['-recebido_em'],
            },
        ),
    ]
