# Generated by Django 5.2.17 on 2026-08-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mensagemwhatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='tipo',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda'), ('RESERVAR', 'Reservar')], max_length=8),
        ),
    ]
