# Generated by Django 5.2.17 on 2026-08-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_operacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='abertura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Abertura (R$)'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='fechamento_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fechamento anterior (R$)'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='hora_cotacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário da cotação (mercado)'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL do logo'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='maxima_52_semanas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Máxima em 52 semanas (R$)'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='maxima_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Máxima do dia (R$)'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='minima_52_semanas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Mínima em 52 semanas (R$)'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='minima_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Mínima do dia (R$)'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='moeda',
            field=models.CharField(blank=True, max_length=8, verbose_name='Moeda'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='nome_longo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome completo'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='valor_mercado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor de mercado (R$)'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='variacao_dia_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Variação no dia (R$)'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Volume negociado'),
        ),
    ]
