# Generated by Django 5.2.17 on 2026-08-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ativo_abertura_ativo_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='lucro_perda_realizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Lucro/perda realizado (R$)'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='preco_medio_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço médio de compra na venda (R$)'),
        ),
    ]
