# Generated by Django 5.2.17 on 2026-08-19 19:02

from django.db import migrations, models


def apagar_vendas_antigas(apps, schema_editor):
    """
    Compra e venda deixam de ser operações separadas (venda agora é um campo
    do próprio lote de compra - ver core.models.Operacao). Os registros
    tipo=VENDA que ainda existirem ficariam órfãos (sem lote correspondente),
    então são removidos aqui.
    """
    Operacao = apps.get_model("core", "Operacao")
    Operacao.objects.filter(tipo="VENDA").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_operacao_lucro_perda_realizado_and_more'),
    ]

    operations = [
        migrations.RunPython(apagar_vendas_antigas, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='operacao',
            name='lucro_perda_realizado',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='preco_medio_venda',
        ),
        migrations.AddField(
            model_name='operacao',
            name='data_venda',
            field=models.DateField(blank=True, null=True, verbose_name='Data da venda'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='preco_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço de venda (R$)'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='quantidade_vendida',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade vendida'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='tipo',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('RESERVAR', 'Reservar')], max_length=8),
        ),
    ]
