# Generated by Django 5.2.17 on 2026-09-01 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_operacao_lucro_perda_realizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonteNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da fonte')),
                ('url', models.URLField(max_length=500, verbose_name='URL da página a ser lida')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fonte de notícias',
                'verbose_name_plural': 'Fontes de notícias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('url', models.URLField(max_length=700, unique=True, verbose_name='Link da matéria')),
                ('capturada_em', models.DateTimeField(auto_now_add=True, verbose_name='Capturada em')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='core.fontenoticia')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-capturada_em'],
            },
        ),
    ]
