# Generated by Django 5.2.17 on 2026-09-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seed_fontes_noticias'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='percentual_corretora',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taxa cobrada pela corretora sobre o total vendido - usada para calcular o valor líquido a receber.', max_digits=5, null=True, verbose_name='Percentual da corretora (%)'),
        ),
    ]
