# Generated by Django 5.2.17 on 2026-09-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_operacao_percentual_corretora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('LUCRO', 'Meta de lucro atingida'), ('PERDA', 'Meta de perda atingida'), ('TENDENCIA', 'Sinal de tendência de mercado'), ('SINAL_COMPRA', 'Robô: sinal de compra'), ('SINAL_VENDA', 'Robô: sinal de venda'), ('LEMBRETE', 'Lembrete geral')], max_length=12),
        ),
    ]
