# Generated by Django 5.2.17 on 2026-09-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_alerta_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoB3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=12, unique=True, verbose_name='Ticker')),
                ('nome', models.CharField(blank=True, max_length=150, verbose_name='Nome')),
                ('setor', models.CharField(blank=True, max_length=150, verbose_name='Setor')),
                ('logo_url', models.URLField(blank=True, max_length=500, verbose_name='URL do logo')),
                ('preco_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço atual (R$)')),
                ('variacao_dia_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Variação do dia (%)')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Ação da B3',
                'verbose_name_plural': 'Ações da B3',
                'ordering': ['ticker'],
            },
        ),
    ]
