# Generated by Django 5.2.17 on 2026-09-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_acaob3"),
    ]

    operations = [
        migrations.AddField(
            model_name="ativo",
            name="setor",
            field=models.CharField(
                blank=True,
                help_text="Preenchido automaticamente pela API de cotações ou pelo catálogo Ações da B3, quando disponível - usado para a análise de concentração por setor da carteira.",
                max_length=150,
                verbose_name="Setor",
            ),
        ),
        migrations.CreateModel(
            name="CotacaoIndice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indice",
                    models.CharField(
                        choices=[("IBOVESPA", "Ibovespa"), ("CDI", "CDI")],
                        max_length=10,
                        verbose_name="Índice",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Pontos do índice (Ibovespa) ou taxa diária em % (CDI).",
                        max_digits=14,
                        verbose_name="Valor",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cotação de índice",
                "verbose_name_plural": "Cotações de índices",
                "ordering": ["indice", "-data"],
                "unique_together": {("indice", "data")},
            },
        ),
    ]
