# Generated by Django 5.2.17 on 2026-09-16 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ativo_setor_cotacaoindice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAtualizacaoCarteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('total_ativos', models.PositiveIntegerField(verbose_name='Total de ativos')),
                ('valor_investido', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor investido')),
                ('valor_atual', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor atual')),
                ('lucro_perda', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Lucro/Perda (R$)')),
                ('lucro_perda_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Lucro/Perda (%)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_atualizacao_carteira', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de atualização da carteira',
                'verbose_name_plural': 'Registros de atualização da carteira',
                'ordering': ['-criado_em'],
            },
        ),
    ]
