# Generated by Django 5.2.17 on 2026-09-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_registroatualizacaocarteira'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoApiBrapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data')),
                ('requisicoes', models.PositiveIntegerField(default=0, verbose_name='Requisições')),
            ],
            options={
                'verbose_name': 'Consumo diário da API brapi.dev',
                'verbose_name_plural': 'Consumo diário da API brapi.dev',
                'ordering': ['-data'],
            },
        ),
    ]
