# Generated by Django 5.2.17 on 2026-09-22 12:48

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_consumoapibrapi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaCorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Saldo inicial (R$)')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_corrente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta corrente',
                'verbose_name_plural': 'Contas correntes',
            },
        ),
        migrations.CreateModel(
            name='LancamentoContaCorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito')], max_length=8, verbose_name='Tipo')),
                ('origem', models.CharField(choices=[('COMPRA', 'Compra de ações'), ('VENDA', 'Venda de ações'), ('TRANSFERENCIA', 'Transferência')], max_length=15, verbose_name='Origem')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor (R$)')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='core.contacorrente')),
                ('operacao', models.ForeignKey(blank=True, help_text='Preenchido só nos lançamentos automáticos de compra/venda - nulo nas transferências manuais.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_conta_corrente', to='core.operacao')),
            ],
            options={
                'verbose_name': 'Lançamento da conta corrente',
                'verbose_name_plural': 'Lançamentos da conta corrente',
                'ordering': ['-data', '-criado_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('operacao__isnull', False)), fields=('operacao', 'origem'), name='um_lancamento_por_operacao_e_origem')],
            },
        ),
    ]
