# Generated by Django 5.2.17 on 2026-09-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contacorrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='volume',
            field=models.BigIntegerField(blank=True, help_text='Vem de graça no mesmo retorno da API que já busca o preço - nulo em registros salvos antes desse campo existir.', null=True, verbose_name='Volume negociado'),
        ),
    ]
