# Generated by Django 5.2.17 on 2026-09-23 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cotacao_volume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostIt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, verbose_name='Texto')),
                ('minimizado', models.BooleanField(default=False, verbose_name='Minimizado')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_it', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post-it',
                'verbose_name_plural': 'Post-its',
            },
        ),
    ]
