# Generated by Django 5.2.17 on 2026-09-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_postit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='maxima',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vem de graça no mesmo retorno da API que já busca o preço - usada no ATR e no suporte/resistência do Scanner Técnico.', max_digits=12, null=True, verbose_name='Máxima do dia (R$)'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='minima',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vem de graça no mesmo retorno da API que já busca o preço - usada no ATR e no suporte/resistência do Scanner Técnico.', max_digits=12, null=True, verbose_name='Mínima do dia (R$)'),
        ),
    ]
