# Generated by Django 5.2.17 on 2026-09-28 17:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cotacao_maxima_minima'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriptoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=12, unique=True, verbose_name='Código (ex: BTC, ETH)')),
                ('nome', models.CharField(blank=True, max_length=150, verbose_name='Nome')),
                ('moeda', models.CharField(default='BRL', max_length=8, verbose_name='Moeda')),
                ('logo_url', models.URLField(blank=True, max_length=500, verbose_name='URL do logo')),
                ('preco_atual', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Preço atual')),
                ('variacao_dia_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Variação no dia (%)')),
                ('variacao_dia_valor', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Variação no dia (valor)')),
                ('maxima_dia', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Máxima do dia')),
                ('minima_dia', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Mínima do dia')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='Volume negociado (24h)')),
                ('valor_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='Valor de mercado')),
                ('hora_cotacao', models.DateTimeField(blank=True, null=True, verbose_name='Horário da cotação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Criptomoeda',
                'verbose_name_plural': 'Criptomoedas',
                'ordering': ['coin'],
            },
        ),
        migrations.CreateModel(
            name='OperacaoCripto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('RESERVAR', 'Reservar')], max_length=8)),
                ('quantidade', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Preço unitário')),
                ('data_operacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da operação')),
                ('meta_lucro_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Meta de lucro (%)')),
                ('meta_perda_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Meta de perda (%) - use valor negativo')),
                ('quantidade_vendida', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, verbose_name='Quantidade vendida')),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Preço de venda')),
                ('data_venda', models.DateField(blank=True, null=True, verbose_name='Data da venda')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cripto_ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacoes', to='core.criptoativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes_cripto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operação de criptomoeda',
                'verbose_name_plural': 'Operações de criptomoeda',
                'ordering': ['-data_operacao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CotacaoCripto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da cotação')),
                ('preco_fechamento', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Preço de fechamento')),
                ('variacao_dia_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Variação no dia (%)')),
                ('maxima', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Máxima do dia')),
                ('minima', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Mínima do dia')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cripto_ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='core.criptoativo')),
            ],
            options={
                'verbose_name': 'Cotação de criptomoeda',
                'verbose_name_plural': 'Cotações de criptomoeda',
                'ordering': ['-data'],
                'unique_together': {('cripto_ativo', 'data')},
            },
        ),
    ]
