# Generated by Django 5.2.17 on 2026-09-28 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cripto_ativo_operacao_cotacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentocontacorrente',
            name='operacao_cripto',
            field=models.ForeignKey(blank=True, help_text='Preenchido só nos lançamentos automáticos de compra/venda de criptomoeda - nulo nos de ações e nas transferências manuais.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_conta_corrente', to='core.operacaocripto'),
        ),
        migrations.AlterField(
            model_name='lancamentocontacorrente',
            name='operacao',
            field=models.ForeignKey(blank=True, help_text='Preenchido só nos lançamentos automáticos de compra/venda de ações - nulo nos de cripto e nas transferências manuais.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_conta_corrente', to='core.operacao'),
        ),
        migrations.AlterField(
            model_name='lancamentocontacorrente',
            name='origem',
            field=models.CharField(choices=[('COMPRA', 'Compra de ações'), ('VENDA', 'Venda de ações'), ('COMPRA_CRIPTO', 'Compra de criptomoeda'), ('VENDA_CRIPTO', 'Venda de criptomoeda'), ('TRANSFERENCIA', 'Transferência')], max_length=15, verbose_name='Origem'),
        ),
        migrations.AddConstraint(
            model_name='lancamentocontacorrente',
            constraint=models.UniqueConstraint(condition=models.Q(('operacao_cripto__isnull', False)), fields=('operacao_cripto', 'origem'), name='um_lancamento_por_operacao_cripto_e_origem'),
        ),
    ]
