# Generated by Django 5.2.17 on 2026-10-09 12:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_registro_atualizacao_carteira_cripto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da cotação (R$)')),
                ('origem', models.CharField(choices=[('AUTOMATICA', 'Automática'), ('MANUAL', 'Manual')], default='AUTOMATICA', max_length=10, verbose_name='Origem')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_cotacao', to='core.ativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_cotacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de cotação',
                'verbose_name_plural': 'Registros de cotações',
                'ordering': ['-data', '-hora', '-id'],
                'indexes': [models.Index(fields=['usuario', 'ativo', 'data', 'hora'], name='core_regist_usuario_be53e2_idx')],
            },
        ),
    ]
