# Generated by Django 5.2.17 on 2026-09-15 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="Formato internacional, só dígitos (ex: 5565999998888). Deixe em branco para não receber avisos automáticos por WhatsApp - os avisos continuam aparecendo em Alertas normalmente.",
                        max_length=20,
                        verbose_name="Número do WhatsApp para avisos",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil do usuário",
                "verbose_name_plural": "Perfis dos usuários",
            },
        ),
    ]
