# Generated by Django 5.2.17 on 2026-10-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='numero_whatsapp',
            field=models.CharField(blank=True, help_text='Formato internacional, só dígitos (ex: 5565999998888). Opcional.', max_length=20, verbose_name='Número do WhatsApp'),
        ),
    ]
