# Generated by Django 5.2.17 on 2026-10-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ajusta_textos_numero_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Token do seu bot, criado no @BotFather (ex: 123456789:AAF...). Opcional.', max_length=100, verbose_name='Token do bot do Telegram'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID do chat que recebe os avisos (ex: 2065125150). Opcional.', max_length=32, verbose_name='Chat ID do Telegram'),
        ),
    ]
