# Generated by Django 5.2.17 on 2026-10-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_telegram_por_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='assinatura_eletronica',
            field=models.CharField(blank=True, help_text='Assinatura que a corretora pede para confirmar ordens no Home Broker. Opcional.', max_length=32, verbose_name='Assinatura eletrônica da corretora'),
        ),
    ]
