# Generated by Django 5.2.17 on 2026-10-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_assinatura_eletronica'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='corretora_senha',
            field=models.CharField(blank=True, help_text='Senha de acesso ao Home Broker. Opcional.', max_length=128, verbose_name='Senha da corretora'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='corretora_usuario',
            field=models.CharField(blank=True, help_text='Login (CPF, e-mail ou código) usado para entrar no Home Broker. Opcional.', max_length=100, verbose_name='Usuário da corretora'),
        ),
    ]
